version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/covid-19-tracker-app/
hooks:
  AfterInstall:
   - location: setup.sh
     runas: root
  ApplicationStart:
   - location: run.sh
     runas: root
