name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Build and run the Docker containers
      run: docker-compose up --build -d
      
    - name: Run tests
      run: docker exec covid-19-tracker-app npm run test
